<?php
Redux::set_section( Minimog_Redux::OPTION_NAME, array(
	'title'      => sprintf( esc_html__( 'Fill %s', 'minimog' ), '01' ),
	'id'         => 'title_bar_fill_01',
	'subsection' => true,
	'fields'     => array(
		/*array(
			'id'             => 'title_bar_fill_01_margin',
			'type'           => 'spacing',
			'mode'           => 'margin',
			'all'            => false,
			'units'          => array( 'em', 'px', '%' ),
			'units_extended' => true,
			'title'          => esc_html__( 'Margin', 'minimog' ),
			'top'            => false,
			'left'           => false,
			'right'          => false,
			'default'        => array(
				'margin-bottom' => '60',
				'units'         => 'px',
			),
		),
		array(
			'id'             => 'title_bar_fill_01_breadcrumb_padding',
			'type'           => 'spacing',
			'mode'           => 'padding',
			'all'            => false,
			'units'          => 'px',
			'units_extended' => false,
			'title'          => esc_html__( 'Breadcrumb Padding', 'minimog' ),
			'left'           => false,
			'right'          => false,
		),
		array(
			'id'             => 'title_bar_fill_01_breadcrumb_min_height',
			'type'           => 'dimensions',
			'units'          => 'px',
			'units_extended' => false,
			'title'          => esc_html__( 'Breadcrumb Min Height', 'minimog' ),
			'width'          => false,
			'default'        => array(
				'height' => 0,
			),
		),*/
		array(
			'id'          => 'title_bar_fill_01_heading_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Heading Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_text_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'      => 'title_bar_fill_01_background',
			'title'   => esc_html__( 'Background', 'minimog' ),
			'type'    => 'background',
			'default' => array(
				'background-color'    => '#EDECEA',
				'background-image'    => MINIMOG_THEME_IMAGE_URI . '/title-bar/fill-01.jpg',
				'background-repeat'   => 'no-repeat',
				'background-position' => 'center center',
				'background-size'     => 'cover',
			),
		),
		array(
			'id'          => 'title_bar_fill_01_background_overlay',
			'type'        => 'color',
			'title'       => esc_html__( 'Background Overlay', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'     => 'title_bar_fill_01_breadcrumb_settings',
			'type'   => 'tm_heading',
			'title'  => esc_html__( 'Breadcrumb', 'minimog' ),
			'indent' => true,
		),
		array(
			'id'      => 'title_bar_fill_01_breadcrumb_text_align',
			'type'    => 'select',
			'title'   => esc_html__( 'Text Align', 'minimog' ),
			'options' => [
				'flex-start' => esc_html__( 'Left', 'minimog' ),
				'center'     => esc_html__( 'Center', 'minimog' ),
				'flex-end'   => esc_html__( 'Right', 'minimog' ),
			],
			'default' => Minimog_Redux::get_default_setting( 'title_bar_fill_01_breadcrumb_text_align' ),
		),
		array(
			'id'          => 'title_bar_fill_01_breadcrumb_text_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_breadcrumb_link_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Link Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_breadcrumb_link_hover_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Link Hover Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_breadcrumb_separator_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Separator Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'     => 'title_bar_fill_01_category_settings',
			'type'   => 'tm_heading',
			'title'  => esc_html__( 'Category', 'minimog' ),
			'indent' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_category_name_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Category Name Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_category_count_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Category Count Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_category_price_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Category Price Color', 'minimog' ),
			'color_alpha' => true,
		),
		array(
			'id'          => 'title_bar_fill_01_category_price_amount_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Category Price Amount Color', 'minimog' ),
			'color_alpha' => true,
		),
	),
) );
